### PR TITLE
Wait for Pod IPs to be assigned in Integration test

### LINKED ISSUE #434: SMI Integration test failure [master branch]
#### Issue

CI Fails with this message:

```

smi_test.go:42:
--
915 | config := s.testConfigurationWithReturn(c, "resources/smi/access-control.json")
915 | integration_test.go:397:
916 | c.Error(err)
918 | ... Error: try operation failed: --- Expected
918 | +++ Got
919 | @@ -6,7 +6,7 @@
920 | "http-5000"
922 | ],
922 | "middlewares": [
924 | -                    "a-b-test-b-test-80-a-b-test-e0425d13b2a322ad-whitelist"
924 | +                    "smi-block-all-middleware"
925 | ],
927 | "service": "b-test-80-a-b-test-e0425d13b2a322ad",
928 | "rule": "(PathPrefix(`/foo`) \u0026\u0026 (Host(`b.test.maesh`) \|\| Host(`XXXX`)))"
928 | @@ -16,7 +16,7 @@
930 | "http-5000"
930 | ],
931 | "middlewares": [
933 | -                    "c-b-test-b-test-80-c-b-test-643c7128c8514ba9-whitelist"
933 | +                    "smi-block-all-middleware"
935 | ],
935 | "service": "b-test-80-c-b-test-643c7128c8514ba9",
937 | "rule": "(PathPrefix(`/foo`) \u0026\u0026 (Host(`b.test.maesh`) \|\| Host(`XXXX`)))"
938 | @@ -26,7 +26,7 @@
938 | "http-5000"
939 | ],
940 | "middlewares": [
942 | -                    "c-d-test-d-test-80-c-d-test-2c7d96b07eb597fd-whitelist"
943 | +                    "smi-block-all-middleware"
943 | ],
945 | "service": "d-test-80-c-d-test-2c7d96b07eb597fd",
946 | "rule": "(PathPrefix(`/bar`) \u0026\u0026 (Host(`d.test.maesh`) \|\| Host(`XXXX`)))"
946 | @@ -40,15 +40,6 @@
947 | }
948 | },
949 | "middlewares": {
951 | -            "a-b-test-b-test-80-a-b-test-e0425d13b2a322ad-whitelist": {
952 | -                "ipWhiteList":{"sourceRange":["XXXX"]}
952 | -            },
954 | -            "c-b-test-b-test-80-c-b-test-643c7128c8514ba9-whitelist": {
954 | -                "ipWhiteList":{"sourceRange":["XXXX"]}
955 | -            },
957 | -            "c-d-test-d-test-80-c-d-test-2c7d96b07eb597fd-whitelist": {
958 | -                "ipWhiteList":{"sourceRange":["XXXX"]}
958 | -            },
959 | "smi-block-all-middleware": {
961 | "ipWhiteList":{"sourceRange":["XXXX"]}
961 | }

```

### PR DESCRIPTION
**Pull request by dtomcej**
This PR:

- Adds waiting functionality for Pod IPs so that we don't create partial configurations.

This should hopefully reduce the failure rate of the SMI provider.

Fixes #434 

I hope.

### CODE REVIEW

**Comment by dtomcej** [comment]
Semaphore liked that the first time around 🚀

File: integration/try/try.go [hunk 1]
```diff
@@ -101,6 +102,36 @@ func (t *Try) WaitDeleteDeployment(name string, namespace string, timeout time.D
 	return nil
 }
 
+// WaitPodIPAssigned wait until the pod is assigned an IP.
+func (t *Try) WaitPodIPAssigned(name string, namespace string, timeout time.Duration) error {
+	ebo := backoff.NewExponentialBackOff()
+	ebo.MaxElapsedTime = applyCIMultiplier(timeout)
+
+	if err := backoff.Retry(safe.OperationWithRecover(func() error {
+		podList, err := t.client.ListPodWithOptions(namespace, metav1.ListOptions{})
```
Comment (jspdown) [inline integration/try/try.go]: Since we are interested in the state of a single pod, could we simply add a `t.client.GetPodWithOptions` or directly call `t.client.KubeClient.CoreV1().Pods(namespace).Get(name, metav1.ListOptions{})` ?

File: integration/smi_test.go [hunk 2]
```diff
@@ -177,3 +186,10 @@ func (s *SMISuite) checkTCPServiceServerURLs(c *check.C, config *dynamic.Configu
 		c.Log("Service " + name + " has the correct expected values.")
 	}
 }
+
+func (s *SMISuite) waitForPodIPs(c *check.C, pods []string) {
+	for _, pod := range pods {
+		c.Log("Waiting for pod: \"" + pod + "\" to have IP assigned.")
```
Comment (jspdown) [inline integration/smi_test.go]: Apparently, `c.Log` relies on `Sprintf` to assemble arguments. It gives us the ability to use the `%q`:
```suggestion
		c.Log("Waiting for pod: %q to have IP assigned.", pod)
```
