### PR TITLE
Fix incomplete topology when destination port is not found

### LINKED ISSUE #581: Incomplete Topology when a Service evaluation fails (sporadic)
### What did you do?

Let say you have created 2 Services and a TrafficTarget. In the TrafficTarget you have defined a destination with a port and a service-account which is used by pods matching the selector of both services. If one of the Services doesn't expose the port mentioned in the TrafficTarget you are going to receive an error:

```
Error building topology for TrafficTarget "tt@ns": unable to find destination ports on Service "svc-2@ns": destination port 80 of TrafficTarget "tt@ns" is not exposed by the service 
```

This error is expected. But if you modify the TrafficTarget specs multiple time and check at the dynamic config, sometimes, there's no router for the first service (the one that was supposed to work).

### What did you expect to see?

I expected to see a router for the first service. 

### What did you see instead?

There's sometimes no services.

### Output of controller log: (_What version of Maesh are you using?_)

Version: master

### What is your environment & configuration (arguments, provider, platform, ...)?

```
helm install maesh helm/chart/maesh \
  --namespace=maesh \
  --set image.pullPolicy=IfNotPresent \
  --set image.name=maesh-dev \
  --set image.tag=latest \
  --set limits.tcp=20 \
  --set limits.http=20 \
  --set smi.deploy=true \
  --set acl=true
```

### PR DESCRIPTION
**Pull request by jspdown**
## What does this PR do?

This PR fixes a bug that happen when a TrafficTarget is applied on more than one Service and one of them is causing an error: If the `TrafficTarget.destination.port` is not present on the targeted service an error gets logged and it won't process next services.

Fixes #581 

In order to fix this behavior, instead of exiting the function on the first error, we just skip the Service.

## How to test it:

- Deploy 2 Service:
  - One which expose port 80
  - One which expose port 8080
- Define a TrafficTarget with a destination port = 80
- Update the TrafficTarget to trigger update (such as modifying the spec of a HTTPRouteGroup)

You should see one router for the traffic target in the dynamic config.

### CODE REVIEW

File: pkg/topology/builder.go [hunk 1]
```diff
@@ -218,9 +218,11 @@ func (b *Builder) evaluateTrafficSplit(topology *Topology, trafficSplit *split.T
...
 
-			return
+			continue
 		}
 
+		var err error
+
 		// As required by the SMI specification, backends must expose at least the same ports as the Service on
 		// which the TrafficSplit is.
 		for _, svcPort := range svc.Ports {
```
Comment (kevinpollet) [inline pkg/topology/builder.go:228]: It's a bit hard to understand these loops. Maybe splitting these loops will make the code easier to understand?

Comment (dtomcej) [reply pkg/topology/builder.go:228]: We refactor this in #550. Did we want to wait for that PR to merge and then update with this fix?

Comment (kevinpollet) [reply pkg/topology/builder.go:228]: You're right, I think it's simpler to merge #550 and then update this fix.

**Comment by jspdown** [comment]
I thought this patch might deserve a unit test. While doing this I discovered an issue in `setTrafficSplitWithErr` and `setTrafficSplitWithErr`. They both missed a lot of property from the the TrafficTarget and TrafficSplit. I fixed this as well.

**Comment by jspdown** [comment]
This PR will be blocked until https://github.com/containous/maesh/pull/564 gets merged.

**Comment by Ullaakut** [comment]
@jspdown Do you need help with this PR? is there something else still blocking it?

**Comment by jspdown** [comment]
@Ullaakut Thanks, that's fine. I just need to rebase it and fix the lint errors.
